package com.springcloud.example.demo.model;

import java.io.Serializable;

public class MoGrade implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mo_grade.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mo_grade.gradename
     *
     * @mbggenerated
     */
    private String gradename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mo_grade.id
     *
     * @return the value of mo_grade.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mo_grade.id
     *
     * @param id the value for mo_grade.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mo_grade.gradename
     *
     * @return the value of mo_grade.gradename
     *
     * @mbggenerated
     */
    public String getGradename() {
        return gradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mo_grade.gradename
     *
     * @param gradename the value for mo_grade.gradename
     *
     * @mbggenerated
     */
    public void setGradename(String gradename) {
        this.gradename = gradename == null ? null : gradename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MoGrade other = (MoGrade) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGradename() == null ? other.getGradename() == null : this.getGradename().equals(other.getGradename()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGradename() == null) ? 0 : getGradename().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gradename=").append(gradename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}