package com.springcloud.example.demo.mapper;

import com.springcloud.example.demo.model.MoGrade;
import org.apache.ibatis.annotations.*;
import org.springframework.context.annotation.Bean;

import java.util.List;

@Mapper
public interface MoGradeMapper {

    @Select("select * from mo_grade where id = #{id}")
    @Results(
            {
                    @Result(property = "id",column = "id"),
                    @Result(property = "gradename",column = "gradename")
            }
    )
    MoGrade getGradeById(int id);

    List<MoGrade> getAllGrades(MoGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    int insert(MoGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    int insertSelective(MoGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    MoGrade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MoGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_grade
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MoGrade record);
}