package com.springcloud.example.demo.mapper;

import com.springcloud.example.demo.model.MoStudent;

public interface MoStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_student
     *
     * @mbggenerated
     */
    int insert(MoStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_student
     *
     * @mbggenerated
     */
    int insertSelective(MoStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_student
     *
     * @mbggenerated
     */
    MoStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MoStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mo_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MoStudent record);
}